import type { Metadata } from 'next'
import './globals.css'
import Navbar from './components/Navbar'
import { montserrat } from './constants'
import Footer from './components/Footer'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Providers } from './providers'
export const metadata: Metadata = {
  title: 'Joel Maraño | Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" suppressHydrationWarning>
      {/* bg-gradient-to-br from-[#120E16] to-[#100b15] */}
      <body className={`${montserrat.className}`}>
      <Providers>
          {children}
      </Providers>
      </body>
    </html>
  )
}
